name: this_4_that
version: 1.0.0+1
publish_to: none
description: Mobile application made for university competition
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  animated_theme_switcher: ^2.0.8
  build_runner: ^2.2.0
  card_swiper: ^2.0.4
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  datepicker_dropdown: ^0.0.7+5
  flutter_card_swiper: ^5.1.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_screenutil: 5.5.4
  flutter_svg: ^2.0.5
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  flutter_firebase_chat_core: any
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.3
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.7+4
  json_serializable: ^6.6.2
  logger_flutter_fork: 1.2.0
  logger_fork: ^1.2.0
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.14
  shadow_overlay: ^1.0.5
  shared_preferences: ^2.1.0

  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.0
  firebase_ui_auth: ^1.4.2
  firebase_ui_firestore: ^1.5.2
  firebase_ui_database: ^1.3.2


  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^1.0.3
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - images/
  uses-material-design: true
